export default {
  FETCH_ARTICLES_REQUEST: '@@articles/FETCH_ARTICLES_REQUEST',
  FETCH_ARTICLES_SUCCESS: '@@articles/FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_ERROR: '@@articles/FETCH_ARTICLES_ERROR'
};
