export default {
  LOGIN_USER_REQUEST: '@@auth/LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: '@@auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: '@@auth/LOGIN_USER_ERROR',

  REGISTER_USER_REQUEST: '@@auth/REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: '@@auth/REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR: '@@auth/REGISTER_USER_ERROR',

  LOGOUT_USER: '@@auth/LOGOUT_USER',

  FETCH_USER_REQUEST: '@@auth/FETCH_USER_REQUEST',
  FETCH_USER_SUCCESS: '@@auth/FETCH_USER_SUCCESS',
  FETCH_USER_ERROR: '@@auth/FETCH_USER_ERROR'
};
